version: '3.9'

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: wallet_user
      POSTGRES_PASSWORD: wallet_pass
      POSTGRES_DB: wallet_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq

  auth_service:
    build: .
    command: ["uvicorn", "auth_service:app", "--host", "0.0.0.0", "--port", "8000"]
    environment:
      JWT_SECRET: supersecret
      JWT_ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 15
      REFRESH_TOKEN_EXPIRE_DAYS: 7
      REDIS_URL: redis://redis:6379/0
      POSTGRES_DB: wallet_db
      POSTGRES_USER: wallet_user
      POSTGRES_PASSWORD: wallet_pass
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      RABBITMQ_URL: amqp://rabbit:rabbit@rabbitmq:5672/
      WALLET_AES_KEY: "32byteslongsecretkeyforaes256!!"
      PRIMARY_HOST: postgres
      PRIMARY_NAME: wallet_db
      PRIMARY_USERNAME: wallet_user
      PRIMARY_PASSWORD: wallet_pass
    depends_on:
      - postgres
      - redis
      - rabbitmq
    ports:
      - "8001:8000"

  user_service:
    build: .
    command: ["uvicorn", "user_service:app", "--host", "0.0.0.0", "--port", "8000"]
    environment:
      JWT_SECRET: supersecret
      JWT_ALGORITHM: HS256
      REDIS_URL: redis://redis:6379/0
      POSTGRES_DB: wallet_db
      POSTGRES_USER: wallet_user
      POSTGRES_PASSWORD: wallet_pass
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      RABBITMQ_URL: amqp://rabbit:rabbit@rabbitmq:5672/
      WALLET_AES_KEY: "32byteslongsecretkeyforaes256!!"
      PRIMARY_HOST: postgres
      PRIMARY_NAME: wallet_db
      PRIMARY_USERNAME: wallet_user
      PRIMARY_PASSWORD: wallet_pass
    depends_on:
      - postgres
      - redis
      - rabbitmq
    ports:
      - "8002:8000"

volumes:
  pgdata:
  redisdata:
  rabbitmqdata: